# Generated by Django 4.2.25 on 2025-10-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cftoken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
